//------------------------------------------------------------
// 此文件由工具自动生成
//------------------------------------------------------------

public enum eAttributeType : int
{
    Unknown = 0,
    CollectionLv = 1,
    CombatLv = 2,
    FarmingLv = 3,
    CollectionExp = 4,
    CombatExp = 5,
    FarmingExp = 6,
    MoveSpd = 7,
    HomeExtraMoveSpd = 8,
    GearAvailableLv = 9,
    HP = 10,
    MaxHP = 11,
    HpRecovery = 12,
    CombatAtt = 13,
    CombatAttSpd = 14,
    CombatDef = 15,
    CombatHit = 16,
    CombatDodge = 17,
    CombatVulnerable = 18,
    CombatCritRate = 19,
    CombatCritDmg = 20,
    CombatDmgBonus = 21,
    TreeAtt = 22,
    AxeSpd = 23,
    TreeCritRate = 24,
    TreeCritDmg = 25,
    TreeDmgBonus = 26,
    ExtraWoodRate = 27,
    TreeAvailableLv = 28,
    OreAtt = 29,
    PickaxeSpd = 30,
    OreCritRate = 31,
    OreCritDmg = 32,
    OreDmgBonus = 33,
    ExtraOreRate = 34,
    OreAvailableLv = 35,
    HoeingEffect = 36,
    HoeSpd = 37,
    WateringEffect = 38,
    ExtraWateringRate = 39,
    ExtraHarvestRate = 40,
    HarvestSeedRate = 41,
    CropAvailableLv = 42,
    FertilityCapacity = 43,
    MaxFertility = 44,
    PetHappinessCapacity = 46,
    MaxPetHappiness = 47,
    PlantingProficiency = 49,
    BreedingProficiency = 50,
    GrassAtt = 51,
    SickleSpd = 52,
    GrassCritRate = 53,
    GrassProficiency = 54,
    TreeProficiency = 55,
    OreProficiency = 56,
    GrassCritDmg = 58,
    GrassDmgBonus = 59,
    GrassDef = 60,
    TreeDef = 61,
    OreDef = 62,
    RequiredProficiency = 63,
    Energy = 64,
    MaxEnergy = 65,
    CombatPotentiality = 66,
    GatherPotentiality = 67,
    FarmPotentiality = 68,
    ExtraGrassRate = 69,
    NeedWaterValue = 71,
    RequiredFertilizer = 72,
    RequirementProficiency = 73,
    PlantingDifficulty = 74,
    WitherTime = 75,
    MaxActionValue = 76,
    RequiredBreedingProficiency = 77,
    WhiteHP = 78,
    MaxWhiteHP = 79,

}

